In [27]:
import numpy as np

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
b = a.reshape(5,3)

In [30]:
a.shape

(15,)

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
b.shape

(5, 3)

In [34]:
b.ndim

2

In [35]:
a.dtype.name

'int64'

In [36]:
b.size

15

In [37]:
type(a)

numpy.ndarray

In [38]:
x = np.array([1,2,3])

In [39]:
x

array([1, 2, 3])

In [40]:
x.dtype

dtype('int64')

In [41]:
y = np.array([(1,2,3), (4,5,6)])

In [42]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [48]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [49]:
np.linspace(0, 5, 14)

array([0.        , 0.38461538, 0.76923077, 1.15384615, 1.53846154,
       1.92307692, 2.30769231, 2.69230769, 3.07692308, 3.46153846,
       3.84615385, 4.23076923, 4.61538462, 5.        ])

In [50]:
from numpy import pi

In [51]:
pi

3.141592653589793

In [52]:
x = np.linspace(0, 2*pi, 10)

x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [53]:
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [54]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [55]:
a - b

array([-3, -3, -3, -3, -3])

In [56]:
a+b

array([ 5,  7,  9, 11, 13])

In [57]:
b**2

array([16, 25, 36, 49, 64])

In [58]:
10 * np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495, -9.58924275])

In [59]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [60]:
b = np.random.random((2,3))
b

array([[0.2703081 , 0.41346791, 0.67045509],
       [0.07421654, 0.32289521, 0.76448739]])

In [61]:
b += a
b

array([[3.2703081 , 3.41346791, 3.67045509],
       [3.07421654, 3.32289521, 3.76448739]])

In [62]:
print (a.sum())

18


In [63]:
a.min()

np.int64(3)

In [64]:
b.max()

np.float64(3.7644873920390203)

In [65]:
b = np.arange(12).reshape(3,4)

In [66]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [68]:
b.sum(axis=1)

array([ 6, 22, 38])

In [69]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [70]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [71]:
a = np.arange(10)**3

In [72]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [73]:
a[5]

np.int64(125)

In [74]:
a[2:5]

array([ 8, 27, 64])

In [75]:
a[-1]

np.int64(729)

In [76]:
for row in b:
    print (row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [77]:
for row in b:
    for i in row:
        print (i, end=" ")
    print ("")

0 1 2 3 
4 5 6 7 
8 9 10 11 


In [78]:
for i in b.flat:
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11


In [79]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
b.shape = (6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [83]:
b.reshape(6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [84]:
b.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [85]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [86]:
b.resize(2,6)

In [87]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [88]:
a = np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
b = np.array([(3,2,5), (14,15,16)])
b

array([[ 3,  2,  5],
       [14, 15, 16]])

In [90]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 3,  2,  5],
       [14, 15, 16]])

In [91]:
np.hstack((a,b))

array([[ 1,  2,  3,  3,  2,  5],
       [ 4,  5,  6, 14, 15, 16]])